[package]
name = "reservoir"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
crc32fast = "1.2"
flume = "0.11"
range-alloc = "0.1"
tokio = { version = "1.34", features = ["rt", "io-util", "time"] }
thiserror = "1.0"
tracing = "0.1"
