[package]
name = "reservoir-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
reservoir = { version = "0.1.0", path = "../reservoir" }
tokio = { version = "1.35", features = ["rt", "io-util", "time"] }

