name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Build [io_uring]
      run: cargo build --verbose --features io_uring
    - name: Lint
      run: cargo clippy -- -Dwarnings
    - name: Run tests
      run: cargo test --verbose
    - name: Run examples
      run: cargo run --example in_memory
